channels:
- pytorch
- anaconda
- defaults
- conda-forge
dependencies:
- python=3.8
- 'pip>=21.0,<22'
- matplotlib
- pytorch
- torchvision
- torchaudio 
- cudatoolkit=11.1
- nvidia-apex==0.1.0
- pip:
  - pyarrow
  - fastparquet
  - mlflow
  - pandas
  - pillow
  - pytorch-lightning==1.3.0rc1
  - jsonargparse[signatures]