channels:
- pytorch
- anaconda
- defaults
- conda-forge
dependencies:
- python=3.8
- 'pip>=21.0,<22'
- pytorch
- cudatoolkit=11.1
- nvidia-apex==0.1.0
- pip:
  - azureml-core
  - azureml-defaults
  - azureml-mlflow
  - azureml-telemetry
  - azureml-train-core
  - mlflow
  - pytorch-lightning==1.3.0rc1
  - jsonargparse[signatures]