$schema: https://azuremlsdk2.blob.core.windows.net/latest/deployment.schema.json
name: my-deployment # perhaps default to workspace
# I don't see a pick list of available models here?
model: 
  name: model-2
  version: 1
  asset_path: ../my_model.pth # find first file with .pt, .pth, .onnx, .pb (etc.)
environment: # why cant this use std training envs as well?
  conda_file: deployment.yml
  name: my-deploy-env
code_configuration:
  code: 
    asset_path: ./src # can we search for a score.py?
  # also - why can't we run a standard flask scoring file?
  scoring_script: score.py

scale_settings:
  scale_type: manual
  instance_count: 2
  min_instances: 1
  max_instances: 2