$schema: https://azuremlsdk2.blob.core.windows.net/latest/environment.schema.json
# can we do a search for a docker file or requirements.txt 
# or a yml file with a conda def and make a decision on how to split 
# from there? 

# also - why can't we run the CLI with just a standard conda file?

name: conda_env
version: 1
docker: # <- default to appropriate AML image based on conda file?
  image: docker.io/ubuntu/ubuntu
conda_file: file:environment.yml # <- inline?
