$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pytorch-lightning13
version: 7
docker:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04
conda_file: file:conda_dependencies.yml