name: model training

on:
  workflow_dispatch:
         
  push:
    branches:
      - main
    paths:
      - tlaloc/*
      - cloud/*.yml
jobs:
  ml-workflow:
    runs-on: ubuntu-latest
    env:
      AML_JOB: earnings_$GITHUB_RUN_ID
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7

    - name: add az ml extension
      run: |
        az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2-public/ml-1.0.0a1-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2-public -y

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_TOKEN}}

    - name: set aml defaults
      run: |
          az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
          az config set defaults.group=${{secrets.AML_RG}}

    - name: run job
      run: |
          az ml job create --file cloud/job.yaml --name earnings_$GITHUB_RUN_ID --stream

    - name: model artifacts
      run: |
          az ml job download --name earnings_$GITHUB_RUN_ID --outputs --download-path ./run
          mkdir model
          cp ./run/earnings_$GITHUB_RUN_ID/outputs/model/model.onnx ./model/model.onnx
          cp ./run/earnings_$GITHUB_RUN_ID/outputs/model/model.pth ./model/model.pth
          cp ./run/earnings_$GITHUB_RUN_ID/outputs/model/params.json ./model/params.json

    - name: register model
      run: |
        LAST_MODEL_VER=$(az ml model show -n earnings-model --query version | tr -d "\r")
        az ml model create --name earnings-model --local-path ./model --version $((LAST_MODEL_VER+1))
        echo $(az ml endpoint show --name earnings-endpoint --query 'deployments | length(@)' | tr -d "\r")

    - name: deploy
      env:
        DEPLOYMENTS: $(az ml endpoint show --name earnings-endpoint --query 'deployments | length(@)' | tr -d "\r")
      if: ${{ contains(env.DEPLOYMENTS,'1') }}
      run: |
        MODEL_VER=$(az ml model show -n earnings-model --query version | tr -d "\r")
        DEPLOY_NAME=$(az ml endpoint show --name earnings-endpoint --query deployments[0].name | tr -d '"')
        echo $MODEL_VER
        echo $DEPLOY_NAME


        


